#ifndef _LCD_H
#define _LCD_H
#include "sys.h"

// #define LED1(n)		(n?HAL_GPIO_WritePin(GPIOB,GPIO_PIN_8,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOB,GPIO_PIN_8,GPIO_PIN_RESET))
// #define LED1_Toggle (HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_8)) //LED1输出电平翻转

// void LED_Init(void); //LED初始化函数

#define LCD_RS_PIN GPIO_PIN_15
#define LCD_RS_PORT GPIOB

#define LCD_CS_PIN GPIO_PIN_9
#define LCD_CS_PORT GPIOD

#define LCD_SCL_PIN GPIO_PIN_13
#define LCD_SCL_PORT GPIOB

#define LCD_SDI_PIN GPIO_PIN_7
#define LCD_SDI_PORT GPIOA

// #define LCD_SDO_Pin GPIO_PIN_14
// #define LCD_SDO_Port GPIOB

#define LCD_BL_PIN GPIO_PIN_13
#define LCD_BL_PORT GPIOD

#define LCD_RS(n)		(n?HAL_GPIO_WritePin(LCD_RS_PORT,LCD_RS_PIN,GPIO_PIN_SET):HAL_GPIO_WritePin(LCD_RS_PORT,LCD_RS_PIN,GPIO_PIN_RESET))
#define LCD_CS(n)		(n?HAL_GPIO_WritePin(LCD_CS_PORT,LCD_CS_PIN,GPIO_PIN_SET):HAL_GPIO_WritePin(LCD_CS_PORT,LCD_CS_PIN,GPIO_PIN_RESET))
#define LCD_SCL(n)		(n?HAL_GPIO_WritePin(LCD_SCL_PORT,LCD_SCL_PIN,GPIO_PIN_SET):HAL_GPIO_WritePin(LCD_SCL_PORT,LCD_SCL_PIN,GPIO_PIN_RESET))
#define LCD_SDI(n)		(n?HAL_GPIO_WritePin(LCD_SDI_PORT,LCD_SDI_PIN,GPIO_PIN_SET):HAL_GPIO_WritePin(LCD_SDI_PORT,LCD_SDI_PIN,GPIO_PIN_RESET))
#define LCD_BL(n)		(n?HAL_GPIO_WritePin(LCD_BL_PORT,LCD_BL_PIN,GPIO_PIN_SET):HAL_GPIO_WritePin(LCD_BL_PORT,LCD_BL_PIN,GPIO_PIN_RESET))

void lcd_init(void);



#endif
